apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/stalwart-entity-122010/github.com/jorgenbusvold/kubernetes-intro/frontend:cv-frontend-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
